# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-03 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contestlink', models.CharField(default='', max_length=500)),
                ('host', models.CharField(default='', max_length=200)),
                ('artist', models.CharField(default='', max_length=200)),
                ('songs', models.CharField(default='', max_length=200)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Electronic', 'Electronic'), ('Indie', 'Indie'), ('Country', 'Country'), ('Jazz', 'Jazz'), ('Rap/Hip Hop', 'Rap/Hip Hop'), ('R&B', 'R&B')], default='Rock', max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('ages', models.CharField(choices=[('16+', '16+'), ('18+', '18+'), ('19+', '19+'), ('21+', '21+'), ('All Ages', 'All Ages')], max_length=200)),
                ('entrymethod', models.CharField(default='', max_length=200)),
                ('concertday', models.DateField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
