# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1, max_length=4),
        ),
    ]
