# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160803_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
